### ISSUE TITLE
方便执行下动态加载quickjs.so的方案吗

### ISSUE THREAD

**Issue by yifei8** [HarlonWang/quickjs-wrapper#14]
即支持动态设置quickjs.so的路径

**Comment by HarlonWang** [comment]
可以支持的，或者你直接提个 MR 也可以哈 :)

**Comment by HarlonWang** [comment]
方便了解下你的需求吗？因为 quickjs 本身已经很小了，感觉做动态加载的意义不是很大哈，另外，如果要动态加载 so 的话，是要将 quickjs.so 单独打包吗？目前我这里是打在一起的，如果不是单独打包的话，只需要把静态代码块的加载逻辑去掉，由外部调用即可

```java
public class QuickJSContext {
    // 移除以下加载代码，由外部来加载
    static {
        System.loadLibrary("quickjs-android-wrapper");
    }
}
```

**Comment by HarlonWang** [comment]
最新版本的 so 库可由外部加载，我先关闭了
