### ISSUE TITLE
QuickJS fork

### ISSUE THREAD

**Issue by vittorioromeo** [HarlonWang/quickjs-wrapper#21]
Hello! I've seen that you have applied some bugfixes and improvements to QuickJS, which seems to be abandoned. Would you please consider forking the original repository yourself and applying your changes on top? I would be happy to use your fork and possibly contribute with more improvements.

Thanks!

**Comment by HarlonWang** [comment]
I want to do that too, I think you're talking about this: https://github.com/HarlonWang/quickjs
