### ISSUE TITLE
Console.log support

### ISSUE THREAD

**Issue by HarlonWang** [HarlonWang/quickjs-wrapper#34]

**Comment by FongMi** [comment]
![IMG_20221209_111253](https://user-images.githubusercontent.com/3471963/206616200-d4954b38-71d9-4d72-aff0-c5cf0b4ab13e.jpg)
I just write simple one

**Comment by FongMi** [comment]
感謝大佬提供 😂
等你內置了💪

**Comment by ijuniorfu** [comment]
大佬就是大佬
