### ISSUE TITLE
Make QuickJSContext implements AutoCloseable

### ISSUE THREAD

**Issue by ag2s20150909** [HarlonWang/quickjs-wrapper#37]
使QuickJSContext实现 AutoCloseable，现在销毁 JSContext 需要执行两个方法，太麻烦了。

**Comment by HarlonWang** [comment]
JSRuntime 和 JSContext 是一对多的关系，会有两种使用场景：
1. 同时销毁 JSContext 和 JSRuntime，这种场景可以通过 AutoCloseable 去管理
所以需要分成两个方法。
