### ISSUE TITLE
大神您好，有個問題想請教

### ISSUE THREAD

**Issue by FongMi** [HarlonWang/quickjs-wrapper#43]
我有個小夥伴用 for in 寫了個簡單的迴圈
發現印出來多了個 "at" ，請問您那邊會出現嗎？

![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/92c99cf8-01d5-4c77-8c26-bf30a48b6256)

**Comment by FongMi** [comment]
ctx.evaluate("let a = [0,1]\n" +
                "let lala=[];\n" +
                "let nana = [{a:1},{a:2}]\n" +
                "for (let vl in nana) {\n" +
                "  lala.push(vl)\n" +
                "}\n" +
                "console.log(lala)");

![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/5e408ecc-d449-4b18-b95b-1974e9d9b70a)

**Comment by qlql765** [comment]
好人一生平安

**Comment by HarlonWang** [comment]
好的，我这边看下

**Comment by HarlonWang** [comment]
找到原因了，是之前支持了 Array.at 的特性导致的，然后原型里定义的 at 被枚举出来了，我想下怎么修，预计明天可以处理，问题代码如下：

**Comment by HarlonWang** [comment]
这个想了下，目前还修不了，因为是为了支持 Array.at 的特性，所以增加了这样的逻辑，另外，如果是数组的话，不会使用 for in 的方式，应该是使用 forEach 进行遍历，你这边的使用场景是什么样的呢？

**Comment by FongMi** [comment]
了解，我請那位有問題的朋友上來回答一下。

**Comment by HarlonWang** [comment]
好的，没关系的，那我就先 close 掉了

**Comment by HarlonWang** [comment]
这个问题我优化了
1. 可以看下这个 commit  https://github.com/HarlonWang/quickjs/commit/0fcdf538b23d4d75d9df9a24b338519b44922ac4
2. 对应的版本：https://github.com/HarlonWang/quickjs-wrapper/releases/tag/0.20.0

**Comment by FongMi** [comment]
好的，感謝，我在測試看看。
