### ISSUE TITLE
請問更新至 0.19.1 有需要調整什麼嗎？

### ISSUE THREAD

**Issue by FongMi** [HarlonWang/quickjs-wrapper#47]
請問更新至 0.19.1 有需要調整什麼嗎？
因為我一樣的程式在 0.19.1 無法運作，沒看到錯誤訊息。

**Comment by HarlonWang** [comment]
无法运作有其他的提示信息吗？或者可以提供测试代码，我这边运行看看？

**Comment by FongMi** [comment]
好，我晚點再詳細測試看看。

**Comment by HarlonWang** [comment]
👌

**Comment by HarlonWang** [comment]
hi，有更多的日志信息么

**Comment by FongMi** [comment]
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/ab1e060f-8c3e-4007-8b81-01cf49f1d892)
好像卡在 QuickJSContext.create();

**Comment by FongMi** [comment]
這是我的程式碼
https://github.com/FongMi/TV/blob/release/drpy/src/main/java/com/hiker/drpy/Spider.java

我操作 quick js 都是透過 executor 的單線程執行

**Comment by HarlonWang** [comment]
我本地拉了你的代码，断点运行了下，没有复现，我的操作如下：

**Comment by FongMi** [comment]
如果你有跑我的專案
可以選擇 leanbackJavaArmeabi_v7aDebug

配置這邊輸入 
http://饭太硬.top/tv
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/27175c0d-54d1-49d0-8c37-534a3b678e27)

站源選擇有聲小說
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/8742cd9b-4787-44dc-a359-fc6d8f51b1b2)

**Comment by HarlonWang** [comment]
我本地拉了你的代码，断点运行了下，我的操作如下：
1. 修改 `drpy` 模块里的 `wrapper-android` 版本至 0.19.1
2. 运行后，发现没有触发 initJS，原因是 initConfig 里的调用的 getCallback 走到 error 的逻辑里
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/921184ec-88f8-43ea-a8a4-7cc7a7df49b8)
3. 尝试在 HomeActivity 里直接触发，测试代码如下：
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/7cc0e6ca-ffa1-4bbf-99cb-7f23999d019f)
4. 可以走到 initJS，createCtx 断点正常，但是因为 api 是测试写的，在 evaluateModule 这里走不过去，可能和你的问题还不太一样

**Comment by HarlonWang** [comment]
好的，我试下用你的配置跑下

**Comment by HarlonWang** [comment]
我这里可以运行呢 😕 
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/c76b95f6-05ee-429f-93cf-df954d621d99)

**Comment by HarlonWang** [comment]
或者再发下你的安装包给我试下

**Comment by FongMi** [comment]
神奇了...

**Comment by FongMi** [comment]
這是我打包的 v7a apk
[leanback-java-armeabi_v7a.zip](https://github.com/HarlonWang/quickjs-wrapper/files/11672370/leanback-java-armeabi_v7a.zip)

**Comment by HarlonWang** [comment]
安装了也没问题，你是什么设备...

**Comment by FongMi** [comment]
雷電模擬器

**Comment by FongMi** [comment]
那我晚點再試試電視上行不行

**Comment by HarlonWang** [comment]
貌似没有 Mac 版本，安装不了这个模拟器 😂 ，你可以试下其他设备有问题吗？我这边用的 Android 的模拟器
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/d3e19866-cbe4-4d28-a35f-71ed1d98c3bc)

**Comment by FongMi** [comment]
好的，感謝您的測試。

**Comment by HarlonWang** [comment]
你可以用下面的快照版本试下，我移除了一个 commit，用来验证是否和这个有关：
1. 在 `setting.gradle` 里添加快照的 repository 地址
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/b57249c2-a07b-439e-8c4e-8e20f7fe816f)
2. 更新至快照版本 `implementation 'wang.harlon.quickjs:wrapper-android:0.19.1-SNAPSHOT'`

**Comment by HarlonWang** [comment]
你可以用下面的快照版本试下，我移除了一个 commit，用来验证是否和这个有关：
1. 在 `setting.gradle` 里添加快照的 repository 地址
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/2297803/b57249c2-a07b-439e-8c4e-8e20f7fe816f)
2. 更新至快照版本 `implementation 'wang.harlon.quickjs:wrapper-android:0.19.1-SNAPSHOT'`

**Comment by FongMi** [comment]
好的，我晚上再找時間測試，非常感謝。

**Comment by HarlonWang** [comment]
我这边有修复掉一个 bug ，不知道是不是和你这边遇到的有关，明天你可以切换到这个版本 `0.19.3` 再看看，改动点：https://github.com/HarlonWang/quickjs-wrapper/commit/aec691d9eccce71787d03ec25ef24749e4fcdac9

**Comment by FongMi** [comment]
0.19.3 測試可以了，感謝。
