### ISSUE TITLE
問題詢問

### ISSUE THREAD

**Issue by FongMi** [HarlonWang/quickjs-wrapper#54]
您好，想請教怎麼讓 QuickJSContext 的 getGlobalObject 可以呼叫 init、home 的 func
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/198a28b1-0cb0-4d85-a4ab-8c9a5173c2f2)

我有將 js 內容丟進去了
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/bbc0c89f-1e08-4fa9-ba6b-17fabd6f17a0)

**Comment by HarlonWang** [comment]
模块导出的对象或者方法，应该没法直接调用的，有一种方式是把这个对象引用给全局对象，通过全局对象去调用，伪代码如下：

`Java`
```Java
QuickJSContext context = QuickJSContext.create();
context.eval("var globalThis = this;");
```
`JavaSript`
```javascript
const jsEvalReturn =  function __jsEvalReturn() { ... }
globalThis.jsEvalReturn = jsEvalReturn;
export jsEvalReturn;
```

`Java`
```Java
QuickJSContext context = QuickJSContext.create();
JSObject globalThis = context.getGlobalObject("globalThis");
JSObject jsEvalReturn = globalThis.getJSObject("jsEvalReturn");
jsEvalReturn.getJSFunction("init")
```

可以试下

**Comment by FongMi** [comment]
好的，感謝，我在試試看。

**Comment by FongMi** [comment]
您好，我在請教一個問題
為什麼我這邊呼叫 home 回傳的值是空的
但是在 js 用 console.log 印出來是有值的
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/24575b26-5bdf-4e13-a109-8f201f8cdad9)

**Comment by FongMi** [comment]
我有看到異步的範例了
只是怎麼把結果提出來呢
![image](https://github.com/HarlonWang/quickjs-wrapper/assets/3471963/1154abf4-bca5-41d0-bae8-4a5dc01c2902)

**Comment by FongMi** [comment]
我好像搞定了。。。
剩下一個問題是，怎麼判斷 getJSFunction 是不是 async 類型的

**Comment by HarlonWang** [comment]
QuickJS 没有提供标准方法来判断，不过可以通过 toString 方法来判断有没有包含 async 关键字来判断，示例如下：
```java
JSFunction test = jsObject.getJSFunction('test');

// 会返回 async function test() {return "123";} 的字符串
String ret = test.getJSFunction("toString").call();

// 判断字符串包含 async 的话，就是 async 类型的函数
if(ret.startWith("async")) {
    // 处理逻辑
}
```

**Comment by FongMi** [comment]
測試OK，非常感謝。

**Comment by FongMi** [comment]
大佬有空能跑跑我的專案嗎
對於第一點我透過 抓到內容置換成 globalThis 的方案有點缺陷
如果對於混淆加密的 js 就會置換失敗
