### ISSUE TITLE
Update quickjs

### ISSUE THREAD

**Issue by samefow** [HarlonWang/quickjs-wrapper#63]
quickjs has been updated on 2024/01/13 to [support ES2023](https://github.com/bellard/quickjs/blob/master/Changelog) completely, so it is time to update the wrapper as well.
Thanks for your effects.

**Comment by HarlonWang** [comment]
I will update recently

**Comment by HarlonWang** [comment]
Updated to the quickjs latest version. You can try using version [2.1.0](https://github.com/HarlonWang/quickjs-wrapper/releases/tag/2.1.0).
