### ISSUE TITLE
[Feature Request] Make QuickJsContext implement Closeable

### ISSUE THREAD

**Issue by dgmltn** [HarlonWang/quickjs-wrapper#64]
Thank you so much for this library 🙏 ! I have an easy suggestion for improvement:

It would be pragmatic to be able to use QuickJSContext with [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) (in Java) or [.use](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) (in Kotlin), like this:

```java
try (QuickJSContext context = QuickJSContext.create()) {
    ...
}
```

```kotlin
QuickJSContext.create().use { context ->
    ...
}
```

But that requires an object that implements `Closeable`.  This should be as simple as adding this method to `QuickJsContext`:
```
public void close() {
    destroy()
}
```

**Comment by HarlonWang** [comment]
ok, I will add it in the next version.
