### ISSUE TITLE
JSObject和JSArray结构设计的有缺陷，特别JSObject无法感知其中数据，不方便转为普通的Map/Object

### ISSUE THREAD

**Issue by ncwuguowei** [HarlonWang/quickjs-wrapper#65]
JSObject中没有一个内部管理的类似map的概念，不知道所有的key值，并且所有的get方法全部是jni native获取，当需要将JSObject转成普通Object(Map）时，无法实现，只能提前预知里面存放的key值数据。
JSArray同样存在获取性能问题，只是多个lenth感知到总长度，每次get时均jni获取。

建议可以参考React Native的中ReadableArray和ReadableMap实现，内部为何一个数据，只需要一次jni接口从底层获取数据。

**Comment by ncwuguowei** [comment]
JSObject#toString方法并不能返回普通js对象的对应json格式文本。
希望提供转Json格式方法，或者提供转map对象方法

**Comment by HarlonWang** [comment]
JSObject.stringify 可以返回 JSON 格式的 String 内容

**Comment by HarlonWang** [comment]
近期会支持转 Map 格式

**Comment by HarlonWang** [comment]
已支持：https://github.com/HarlonWang/quickjs-wrapper/releases/tag/2.2.1
