### ISSUE TITLE
how to get and run Function 

### ISSUE THREAD

**Issue by WavePlayz** [HarlonWang/quickjs-wrapper#67]
my code, says not a function
```java
app.set( "queue", args -> {
			try {
				
				int delay = args.length > 1 ? (int) args[1] : 0;
				
				
				
				task.run(() -> {try {
					JSFunction func = (JSFunction) args[0];
				
					func.call(new Object[]{"wave"});
				} catch (Exception e0) {
					runOnUiThread(() -> toast(e0.toString()));
				}}, delay); 
			} catch (Exception e) {
				
				runOnUiThread(() -> toast(e.getMessage()));
			}
		});

```

**Comment by HarlonWang** [comment]
改成下面这样试试呢：
```kotlin
app.set( "queue", args -> {
			try {
				
				int delay = args.length > 1 ? (int) args[1] : 0;
				JSFunction func = (JSFunction) args[0];
				task.run(() -> {try {
				        func.call(new Object[]{"wave"});
				} catch (Exception e0) {
					runOnUiThread(() -> toast(e0.toString()));
				}}, delay); 
			} catch (Exception e) {
				
				runOnUiThread(() -> toast(e.getMessage()));
			}
		});
```

**Comment by HarlonWang** [comment]
It'll probably take about two to three weeks.

**Comment by HarlonWang** [comment]
> > 改成下面这样试试呢：
> > ```kotlin
> > app.set( "queue", args -> {
> > 			try {
> > 				
> > 				int delay = args.length > 1 ? (int) args[1] : 0;
> > 				JSFunction func = (JSFunction) args[0];
> > 				task.run(() -> {try {
> > 				        func.call(new Object[]{"wave"});
> > 				} catch (Exception e0) {
> > 					runOnUiThread(() -> toast(e0.toString()));
> > 				}}, delay); 
> > 			} catch (Exception e) {
> > 				
> > 				runOnUiThread(() -> toast(e.getMessage()));
> > 			}
> > 		});
> > ```
> 
> oh thanks, also when are you updating to latest quickjs


It'll probably take about two to three weeks.

**Comment by HarlonWang** [comment]
Updated to the quickjs latest version. You can try using version [2.1.0](https://github.com/HarlonWang/quickjs-wrapper/releases/tag/2.1.0).
